import time


print("                                ")
time.sleep(0.2)
print("                                ")
time.sleep(0.2)
print("   TTTTTTTTTTTTTTTTTTTTTTTTT    ")
time.sleep(0.2)
print("   TTTTTTTTTTTTTTTTTTTTTTTTT    ")
time.sleep(0.2)
print("   TTTTTTTTTTTTTTTTTTTTTTTTT    ")
time.sleep(0.2)
print("   TTTTTTTTTTTTTTTTTTTTTTTTT    ")
time.sleep(0.2)
print("            TTTTTT              ")
time.sleep(0.2)
print("            TTTTTT              ")
time.sleep(0.2)
print("            TTTTTT              ")
time.sleep(0.2)
print("            TTTTTT              ")
time.sleep(0.2)
print("            TTTTTT              ")
time.sleep(0.2)
print("            TTTTTT              ")
time.sleep(0.2)
print("            TTTTTT              ")
time.sleep(0.2)
print("            TTTTTT              ")
time.sleep(0.2)
print("            TTTTTT              ")
time.sleep(0.2)
print("            TTTTTT              ")
print("                                ")
print("                                ")


