
import time

start_over = 1

question = input("Wachtwoord voor het gedicht?: ")
if question == "ma":
    start_over -= 1
else:
    raise SystemExit
time.sleep(1)
print('.')
time.sleep(0.5)
print('Aan het verbinden met database.')
time.sleep(1)
print('Gegevens aan het controleren.')
time.sleep(1)
print('Gegevens correct!')
time.sleep(1)
print('.')
time.sleep(1)
print('Welkom bij Tijmen zijn gedicht!')
time.sleep(2)
print('Ik ga je nu een verhaaltje vertellen.')
time.sleep(2)

question = input("Ben je er klaar voor?: ")
if question == "ja":
    start_over -= 1

time.sleep(2)
print('Maakt me niet uit wat je er van vind ik ga het toch vertellen lol.')
time.sleep(1)
print('ok')
time.sleep(0.5)
print('daar')
time.sleep(0.5)
print('gaan')
time.sleep(0.5)
print('we')
time.sleep(0.5)
print('dan')
time.sleep(0.5)
print('verwacht')
time.sleep(0.5)
print('er')
time.sleep(0.5)
print('alleen')
time.sleep(0.5)
print('niet')
time.sleep(0.5)
print('teveel')
time.sleep(0.5)
print('van')
time.sleep(0.5)
print(' ')
time.sleep(0.5)


print('  ')
print('Ik ben Tijmen, 16 jaar en ik woon in Opperdoes. Mijn hobbys zijn gamen en sporten.')
print(' ')
time.sleep(4)
print('Ik ga elke dag met de bus en trein naar school, dat is ongeveer zo een 1,5 uur reizen!')
print(' ')
time.sleep(4)
print('Ik hoop hier op het Media College veel te leren, ik heb er namelijk enorm veel zin in!')
print(' ')
time.sleep(4)
print('Over sporten: Ik sport ongeveer 4x in de week, mijn idool is Joel Beukers.')
print(' ')
time.sleep(4)
print('En ik kijk altijd naar al zijn videos omdat ik wil meer leren!')
print(' ')
time.sleep(4)
print('Over gamen: Volgens mijn steam account heb ik afgelopen 2 weken 60 uur gegamed!')
print(' ')
time.sleep(4)
print('Maar dit vind ik zelf meevallen omdat ik werk aan een eigen gameserver.')
print(' ')
time.sleep(4)
print('Ik ben daar nu druk mee bezig en ik hoop dat er veel spelers op komen als hij af is.')
print(' ')
time.sleep(4)
print('Dit was een klein verhaaltje ik hoop dat je er van genoten hebt en meer van mij weet nu.')
print(' ')

question = input("Wat vond u van het gedicht van een schaal van 1/10?: ")
if question == "10":
    start_over -= 1
else:
    print ('Geen 10 maar alsnog')
time.sleep(1)
print ('Bedankt!')
time.sleep(1)
print ('U word uitgelogd in:')
time.sleep(1)
print ('5')
time.sleep(1)
print ('4')
time.sleep(1)
print ('3')
time.sleep(1)
print ('2')
time.sleep(1)
print ('1')
time.sleep(1)
print ('0')
time.sleep(1)
print ('.')
time.sleep(1)
print ('Uitloggen')
time.sleep(1)
print ('Uw antwoord is opgeslagen en u bent succesvol uitgelogd!')
time.sleep(1)
print ('.')
time.sleep(1)
print ('Fijne dag verder!')
time.sleep(1)
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')

time.sleep(2)
question = input("Wachtwoord voor het gedicht?: ")
if question == "ma":
    start_over -= 1
else:
    raise SystemExit
time.sleep(1)
print('.')
time.sleep(0.5)
print('Aan het verbinden met database.')
time.sleep(1)
print('Gegevens aan het controleren.')
time.sleep(1)
print('Gegevens correct!')
time.sleep(1)
print('.')
time.sleep(1)
print('Welkom bij Tijmen zijn gedicht!')
time.sleep(2)
print('Ik ga je nu een verhaaltje vertellen.')
time.sleep(2)

question = input("Ben je er klaar voor?: ")
if question == "ja":
    start_over -= 1

time.sleep(2)
print('Maakt me niet uit wat je er van vind ik ga het toch vertellen lol.')
time.sleep(1)
print('ok')
time.sleep(0.5)
print('daar')
time.sleep(0.5)
print('gaan')
time.sleep(0.5)
print('we')
time.sleep(0.5)
print('dan')
time.sleep(0.5)
print('verwacht')
time.sleep(0.5)
print('er')
time.sleep(0.5)
print('alleen')
time.sleep(0.5)
print('niet')
time.sleep(0.5)
print('teveel')
time.sleep(0.5)
print('van')
time.sleep(0.5)
print(' ')
time.sleep(0.5)


print('  ')
print('Ik ben Tijmen, 16 jaar en ik woon in Opperdoes. Mijn hobbys zijn gamen en sporten.')
print(' ')
time.sleep(4)
print('Ik ga elke dag met de bus en trein naar school, dat is ongeveer zo een 1,5 uur reizen!')
print(' ')
time.sleep(4)
print('Ik hoop hier op het Media College veel te leren, ik heb er namelijk enorm veel zin in!')
print(' ')
time.sleep(4)
print('Over sporten: Ik sport ongeveer 4x in de week, mijn idool is Joel Beukers.')
print(' ')
time.sleep(4)
print('En ik kijk altijd naar al zijn videos omdat ik wil meer leren!')
print(' ')
time.sleep(4)
print('Over gamen: Volgens mijn steam account heb ik afgelopen 2 weken 60 uur gegamed!')
print(' ')
time.sleep(4)
print('Maar dit vind ik zelf meevallen omdat ik werk aan een eigen gameserver.')
print(' ')
time.sleep(4)
print('Ik ben daar nu druk mee bezig en ik hoop dat er veel spelers op komen als hij af is.')
print(' ')
time.sleep(4)
print('Dit was een klein verhaaltje ik hoop dat je er van genoten hebt en meer van mij weet nu.')
print(' ')

question = input("Wat vond u van het gedicht van een schaal van 1/10?: ")
if question == "10":
    start_over -= 1
else:
    print ('Geen 10 maar alsnog bedankt!')
time.sleep(1)

print ('Bedankt voor de 10')
time.sleep(1)
print ('U word uitgelogd in:')
time.sleep(1)
print ('5')
time.sleep(1)
print ('4')
time.sleep(1)
print ('3')
time.sleep(1)
print ('2')
time.sleep(1)
print ('1')
time.sleep(1)
print ('0')
time.sleep(1)
print ('.')
time.sleep(1)
print ('Uitloggen')
time.sleep(1)
print ('Uw antwoord is opgeslagen en u bent succesvol uitgelogd!')
time.sleep(1)
print ('.')
time.sleep(1)
print ('Fijne dag verder!')
time.sleep(1)
print ('.')
