import time

print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)
print ('lol')
time.sleep(0.05)